Update requirements.txt (#43)
New versions:
AttributeError: module 'jinja2' has no attribute 'contextfilter'
So, to special version of mkdocs, we need jinja2=3.0.3
https://forums.docker.com/t/jinja-mkdocs-issue-breaks-docker101tutorial/122671